export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
export const FETCH_RESTAURANT = "FETCH_RESTAURANT";
export const SORT_RESTAURANTS = "SORT_RESTAURANTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_TO_CART = "UPDATE_TO_CART";
export const DELETE_TO_CART = "DELETE_TO_CART";
