export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
export const FETCH_RESTAURANT = "FETCH_RESTAURANT";
export const SORT_RESTAURANTS = "SORT_RESTAURANTS";

export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_TO_CART = "UPDATE_TO_CART";
export const UPDATE_ADDRESS_TO_CART = "UPDATE_ADDRESS_TO_CART";
export const DELETE_TO_CART = "DELETE_TO_CART";
export const REMOVE_CART = "REMOVE_CART";


export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";


